# Generated by Django 4.2.7 on 2023-12-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_sale_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
