# Generated by Django 5.0 on 2024-02-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_product_store_sale_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
